# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1b4f723f317515af2d1f7c9f32a4c3f7858e0a65d97cd44eb43ece7c5741d52c6e709d2398412473791336e1c5db4785cbe424de0da14cbcd362abd1c2da42

test:
  secret_key_base: c1507460c7df98d1b1694fa141a4759d82b3130cdba686963d985fb50794304c13a788b8158e4f0943ed1324a33acedfbed6442cc98a6a0aabd081aa44344f70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
